// Мышцы упражнений (primary/secondary) из free-exercise-db (Unlicense/public domain),
// по выверенным матчам к нашему каталогу (ключ — русское имя). Слаги датасета;
// маппинг на наши 13 групп — в muscles.ts (FEDB_TO_MUSCLE). Только логика расчёта,
// картинки датасета НЕ используем (забракованы).

export interface FedbMuscles { p: string[]; s: string[] }
export const EXERCISE_MUSCLES: Record<string, FedbMuscles> = {
  "Австралийские подтягивания": { p: ["middle back"], s: ["lats"] },
  "Вакуум живота": { p: ["abdominals"], s: [] },
  "Взятие на грудь": { p: ["hamstrings"], s: ["calves", "forearms", "glutes", "lower back", "middle back", "quadriceps", "shoulders", "traps", "triceps"] },
  "Выпады в ходьбе": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings"] },
  "Выпады с гантелями": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings"] },
  "Выпады со штангой": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings"] },
  "Гакк-приседания": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings"] },
  "Дровосек в кроссовере": { p: ["abdominals"], s: ["shoulders"] },
  "Жим Арнольда": { p: ["shoulders"], s: ["triceps"] },
  "Жим в тренажёре на плечи": { p: ["shoulders"], s: ["triceps"] },
  "Жим гантелей лёжа": { p: ["chest"], s: ["shoulders", "triceps"] },
  "Жим гантелей на наклонной скамье": { p: ["chest"], s: ["shoulders", "triceps"] },
  "Жим гантелей на скамье с обратным наклоном": { p: ["chest"], s: ["shoulders", "triceps"] },
  "Жим гантелей сидя": { p: ["shoulders"], s: ["triceps"] },
  "Жим гантелей стоя": { p: ["shoulders"], s: ["triceps"] },
  "Жим ногами": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings"] },
  "Жим штанги лёжа": { p: ["chest"], s: ["shoulders", "triceps"] },
  "Жим штанги лёжа узким хватом": { p: ["triceps"], s: ["chest", "shoulders"] },
  "Жим штанги на наклонной скамье": { p: ["chest"], s: ["shoulders", "triceps"] },
  "Жим штанги на скамье с обратным наклоном": { p: ["chest"], s: ["shoulders", "triceps"] },
  "Жим штанги сидя": { p: ["shoulders"], s: ["triceps"] },
  "Жим штанги стоя": { p: ["shoulders"], s: ["triceps"] },
  "Кикбэк с гантелью": { p: ["triceps"], s: [] },
  "Колесо для пресса стоя": { p: ["abdominals"], s: ["shoulders"] },
  "Концентрированные сгибания": { p: ["biceps"], s: ["forearms"] },
  "Махи гантелями в стороны": { p: ["shoulders"], s: [] },
  "Махи гантелями в стороны сидя": { p: ["shoulders"], s: [] },
  "Махи гантелями перед собой": { p: ["shoulders"], s: [] },
  "Молотки на скамье Скотта": { p: ["biceps"], s: ["forearms"] },
  "Молотковые сгибания": { p: ["biceps"], s: [] },
  "Мёртвый жук": { p: ["abdominals"], s: [] },
  "Наклоны в сторону с гантелью": { p: ["abdominals"], s: [] },
  "Наклоны с гантелями на прямых ногах": { p: ["hamstrings"], s: ["glutes", "lower back"] },
  "Наклоны со штангой (гуд морнинг)": { p: ["hamstrings"], s: ["abdominals", "glutes", "lower back"] },
  "Обратная гиперэкстензия": { p: ["hamstrings"], s: ["calves", "glutes"] },
  "Обратные отжимания от скамьи": { p: ["triceps"], s: ["chest", "shoulders"] },
  "Обратные скручивания": { p: ["abdominals"], s: [] },
  "Отведение ноги назад в кроссовере": { p: ["glutes"], s: ["hamstrings"] },
  "Отведение ноги назад в тренажёре": { p: ["glutes"], s: ["hamstrings"] },
  "Отжимания алмазные": { p: ["triceps"], s: ["chest", "shoulders"] },
  "Отжимания на брусьях": { p: ["chest"], s: ["shoulders", "triceps"] },
  "Отжимания на брусьях на трицепс": { p: ["triceps"], s: ["chest", "shoulders"] },
  "Отжимания на кольцах": { p: ["triceps"], s: ["chest", "shoulders"] },
  "Отжимания от пола": { p: ["chest"], s: ["shoulders", "triceps"] },
  "Отжимания с ногами на возвышении": { p: ["chest"], s: ["shoulders", "triceps"] },
  "Отжимания с широкой постановкой рук": { p: ["chest"], s: ["abdominals", "shoulders", "triceps"] },
  "Паучьи сгибания": { p: ["biceps"], s: [] },
  "Планка": { p: ["abdominals"], s: [] },
  "Подтягивания обратным хватом": { p: ["lats"], s: ["biceps", "forearms", "middle back"] },
  "Подтягивания прямым хватом": { p: ["lats"], s: ["biceps", "middle back"] },
  "Подъём EZ-штанги на бицепс": { p: ["biceps"], s: [] },
  "Подъём блина перед собой": { p: ["shoulders"], s: [] },
  "Подъём гантелей на бицепс": { p: ["biceps"], s: ["forearms"] },
  "Подъём гантелей на бицепс сидя": { p: ["biceps"], s: [] },
  "Подъём коленей в висе": { p: ["abdominals"], s: [] },
  "Подъём корпуса с блином": { p: ["abdominals"], s: [] },
  "Подъём ног в висе": { p: ["abdominals"], s: [] },
  "Подъём ног лёжа": { p: ["abdominals"], s: [] },
  "Подъём штанги на бицепс": { p: ["biceps"], s: ["forearms"] },
  "Подъём штанги на бицепс обратным хватом": { p: ["biceps"], s: ["forearms"] },
  "Подъёмы на носки в жиме ногами": { p: ["calves"], s: [] },
  "Подъёмы на носки сидя": { p: ["calves"], s: [] },
  "Подъёмы на носки стоя": { p: ["calves"], s: [] },
  "Присед со штангой над головой": { p: ["quadriceps"], s: ["abdominals", "calves", "glutes", "hamstrings", "lower back", "shoulders", "triceps"] },
  "Приседания гоблет": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings", "shoulders"] },
  "Приседания с гантелями": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings", "lower back"] },
  "Приседания с прыжком": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings"] },
  "Приседания со штангой на груди": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings"] },
  "Приседания со штангой на спине": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings", "lower back"] },
  "Прогулка фермера": { p: ["forearms"], s: ["abdominals", "glutes", "hamstrings", "lower back", "quadriceps", "traps"] },
  "Пуловер с гантелью": { p: ["chest"], s: ["lats", "shoulders", "triceps"] },
  "Разведение гантелей лёжа": { p: ["chest"], s: [] },
  "Разведение гантелей на наклонной скамье": { p: ["chest"], s: ["shoulders"] },
  "Разведение ног в тренажёре": { p: ["abductors"], s: ["glutes"] },
  "Разгибания в тренажёре на трицепс": { p: ["triceps"], s: [] },
  "Разгибания на трицепс в блоке": { p: ["triceps"], s: [] },
  "Разгибания на трицепс с канатом": { p: ["triceps"], s: [] },
  "Разгибания ног в тренажёре": { p: ["quadriceps"], s: [] },
  "Ролик для пресса": { p: ["abdominals"], s: ["shoulders"] },
  "Румынская тяга": { p: ["hamstrings"], s: ["calves", "glutes", "lower back"] },
  "Русские скручивания": { p: ["abdominals"], s: ["lower back"] },
  "Салазки (толкание саней)": { p: ["quadriceps"], s: ["calves", "chest", "glutes", "hamstrings", "triceps"] },
  "Сведение ног в тренажёре": { p: ["adductors"], s: ["glutes", "hamstrings"] },
  "Сведение рук в кроссовере": { p: ["chest"], s: ["shoulders"] },
  "Сведение рук в кроссовере снизу": { p: ["chest"], s: ["shoulders"] },
  "Сгибания запястий со штангой": { p: ["forearms"], s: [] },
  "Сгибания на скамье Скотта": { p: ["biceps"], s: [] },
  "Сгибания ног лёжа": { p: ["hamstrings"], s: [] },
  "Сгибания ног сидя": { p: ["hamstrings"], s: [] },
  "Сгибания ног стоя": { p: ["hamstrings"], s: [] },
  "Скручивания в тренажёре": { p: ["abdominals"], s: [] },
  "Скручивания на верхнем блоке (молитва)": { p: ["abdominals"], s: [] },
  "Скручивания на наклонной скамье": { p: ["abdominals"], s: [] },
  "Скручивания на полу": { p: ["abdominals"], s: [] },
  "Скручивания с мячом": { p: ["abdominals"], s: [] },
  "Становая тяга": { p: ["lower back"], s: ["calves", "forearms", "glutes", "hamstrings", "lats", "middle back", "quadriceps", "traps"] },
  "Становая тяга рывковым хватом": { p: ["hamstrings"], s: ["forearms", "glutes", "hamstrings", "lower back", "quadriceps", "traps"] },
  "Становая тяга сумо": { p: ["hamstrings"], s: ["adductors", "forearms", "glutes", "lower back", "middle back", "quadriceps", "traps"] },
  "Степ-ап с гантелями": { p: ["quadriceps"], s: ["calves", "glutes", "hamstrings"] },
  "Толчок штанги": { p: ["shoulders"], s: ["abdominals", "glutes", "hamstrings", "lower back", "quadriceps", "traps", "triceps"] },
  "Тяга Т-грифа": { p: ["middle back"], s: ["biceps", "lats"] },
  "Тяга верхнего блока к груди": { p: ["lats"], s: ["biceps", "middle back", "shoulders"] },
  "Тяга верхнего блока одной рукой": { p: ["lats"], s: ["biceps", "middle back"] },
  "Тяга верхнего блока узким хватом": { p: ["lats"], s: ["biceps", "middle back", "shoulders"] },
  "Тяга гантелей к подбородку": { p: ["traps"], s: ["biceps", "shoulders"] },
  "Тяга горизонтального блока": { p: ["middle back"], s: ["biceps", "lats", "shoulders"] },
  "Тяга к лицу с верхнего блока": { p: ["shoulders"], s: ["middle back"] },
  "Тяга каната к лицу": { p: ["shoulders"], s: ["middle back"] },
  "Тяга штанги в наклоне": { p: ["middle back"], s: ["biceps", "lats", "shoulders"] },
  "Тяга штанги к подбородку": { p: ["shoulders"], s: ["traps"] },
  "Французский жим лёжа": { p: ["triceps"], s: [] },
  "Французский жим с гантелью": { p: ["triceps"], s: ["chest", "shoulders"] },
  "Швунг жимовой": { p: ["shoulders"], s: ["quadriceps", "triceps"] },
  "Шраги с гантелями": { p: ["traps"], s: [] },
  "Шраги со штангой": { p: ["traps"], s: [] },
  "Ягодичный мост с гантелью": { p: ["glutes"], s: ["calves", "hamstrings"] },
  "Ягодичный мост со штангой": { p: ["glutes"], s: ["calves", "hamstrings"] },
};
